services:
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8888:8888"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://api:8080

  api:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: kanastra
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  db:
    image: mysql:8.0
    container_name: database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=kanastra
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6.2
    container_name: redis

volumes:
  db_data:
