version: '3.8'

services:
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8888:8888"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://api:8080

  api:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  worker:
    build:
      context: ./backend
    container_name: celery_worker
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  db:
    image: mysql:8.0
    container_name: database
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  db_data:
