
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: example
          MYSQL_DATABASE: kanastra
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
      redis:
        image: redis:6.2
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Add .env file to backend
      run: echo "${{ secrets.ENV_VARS }}" > backend/.env

    - name: Run tests
      env:
        REDIS_HOST: redis
        REDIS_PORT: 6379
        REDIS_DB: 0
        CELERY_BROKER_URL: redis://redis:6379/0
        CELERY_RESULT_BACKEND: redis://redis:6379/0
        DB_HOST: db
        DB_PORT: 3306
        DB_USER: root
        DB_PASSWORD: example
        DB_NAME: kanastra
        SMTP_SERVER: smtp.example.com
        SMTP_PORT: 587
        SMTP_USERNAME: username
        SMTP_PASSWORD: password
        SMTP_FROM_EMAIL: no-reply@example.com
      run: |
        docker-compose up -d
        pytest backend/tests
